In [16]:
using Distributions

In [26]:
li = zeros(Int64, 2, 3)
li[1, 1] = 100
li

2x3 Array{Int64,2}:
 100  0  0
   0  0  0

In [27]:
li2 = li
li3 = copy(li)
li4 = deepcopy(li)
li[2, 2] = 1000

1000

In [28]:
li

2x3 Array{Int64,2}:
 100     0  0
   0  1000  0

In [29]:
li2

2x3 Array{Int64,2}:
 100     0  0
   0  1000  0

In [30]:
li3

2x3 Array{Int64,2}:
 100  0  0
   0  0  0

copy() でも deepcopyされている. なぜ……

In [31]:
li4

2x3 Array{Int64,2}:
 100  0  0
   0  0  0

In [32]:
li3[3] = 100
li

2x3 Array{Int64,2}:
 100     0  0
   0  1000  0

In [33]:
li2

2x3 Array{Int64,2}:
 100     0  0
   0  1000  0

In [35]:
methods(log)

# 19 methods for generic function "log":
log(a::Complex{Float16}) at float16.jl:151
log{T<:AbstractFloat}(z::Complex{T<:AbstractFloat}) at complex.jl:319
log(z::Complex{T<:Real}) at complex.jl:338
log(x::Float64) at math.jl:137
log(x::Float32) at math.jl:138
log(a::Float16) at float16.jl:150
log(x::BigFloat) at mpfr.jl:549
log(::Irrational{:e}) at irrationals.jl:130
log(::Irrational{:e}, x) at irrationals.jl:131
log(x::Real) at math.jl:139
log{T<:Number}(b::T<:Number, x::T<:Number) at math.jl:101
log(b::Number, x::Number) at math.jl:102
log{T1<:Number,T2<:Number}(::T1<:Number, ::AbstractArray{T2<:Number,N}) at operators.jl:391
log{Tv}(A::SparseMatrixCSC{Tv,Ti<:Integer}) at sparse/sparsematrix.jl:725
log{T<:Number}(::AbstractArray{T<:Number,1}) at operators.jl:380
log{T<:Number}(::AbstractArray{T<:Number,2}) at operators.jl:381
log{T1<:Number,T2<:Number}(::AbstractArray{T1<:Number,N}, ::T2<:Number) at operators.jl:393
log{T1<:Number,T2<:Number}(::AbstractArray{T1<:Number,N}, ::AbstractArray{T2<:Number,N}) at operators.jl:397
log{T<:Number}(::AbstractArray{T<:Number,N}) at operators.jl:383

# Excercise1